#!/usr/bin/env python3

import argparse
import math
import os
import time

from IMU import IMU


def mean(values):
	return sum(values) / len(values) if values else 0.0


def stddev(values, avg):
	if not values:
		return 0.0
	return math.sqrt(sum((v - avg) * (v - avg) for v in values) / len(values))


def main():
	parser = argparse.ArgumentParser(description="IMU 10-second level calibration")
	parser.add_argument("--seconds", type=float, default=10.0, help="Calibration duration in seconds")
	parser.add_argument("--dt", type=float, default=0.02, help="Sample interval in seconds")
	args = parser.parse_args()

	imu = IMU()
	ax_list, ay_list, az_list = [], [], []
	gx_list, gy_list, gz_list = [], [], []
	pitch_list, roll_list = [], []

	start = time.monotonic()
	end_time = start + args.seconds
	print(f"Start calibration: keep IMU level and still for {args.seconds:.1f}s")

	try:
		while time.monotonic() < end_time:
			pitch, roll, ax, ay, az, gx, gy, gz = imu.read()
			pitch_list.append(pitch)
			roll_list.append(roll)
			ax_list.append(ax)
			ay_list.append(ay)
			az_list.append(az)
			gx_list.append(gx)
			gy_list.append(gy)
			gz_list.append(gz)
			remain = max(0.0, end_time - time.monotonic())
			print(f"remain={remain:4.1f}s  P={pitch:6.2f}  R={roll:6.2f}  GZ={gz:6.2f}")
			time.sleep(args.dt)
	except KeyboardInterrupt:
		print("Calibration interrupted by user.")
	finally:
		imu.close()

	n = len(ax_list)
	if n == 0:
		raise SystemExit("No samples collected; calibration file was not created.")

	ax_avg, ay_avg, az_avg = mean(ax_list), mean(ay_list), mean(az_list)
	gx_avg, gy_avg, gz_avg = mean(gx_list), mean(gy_list), mean(gz_list)
	pitch_avg, roll_avg = mean(pitch_list), mean(roll_list)

	accel_norm_avg = mean([math.sqrt(ax * ax + ay * ay + az * az) for ax, ay, az in zip(ax_list, ay_list, az_list)])

	# Level-still baseline offsets (target: ax=0g, ay=0g, az=+1g, gyro=0dps)
	ax_offset = -ax_avg
	ay_offset = -ay_avg
	az_offset = 1.0 - az_avg
	gx_offset = -gx_avg
	gy_offset = -gy_avg
	gz_offset = -gz_avg

	folder = os.path.dirname(os.path.abspath(__file__))
	out_path = os.path.join(folder, "imu_cali.txt")

	lines = [
		"# IMU calibration generated by IMU_Cali.py",
		f"timestamp_unix={int(time.time())}",
		f"duration_sec={args.seconds}",
		f"sample_interval_sec={args.dt}",
		f"sample_count={n}",
		f"pitch_avg_deg={pitch_avg:.6f}",
		f"roll_avg_deg={roll_avg:.6f}",
		f"ax_avg_g={ax_avg:.6f}",
		f"ay_avg_g={ay_avg:.6f}",
		f"az_avg_g={az_avg:.6f}",
		f"gx_avg_dps={gx_avg:.6f}",
		f"gy_avg_dps={gy_avg:.6f}",
		f"gz_avg_dps={gz_avg:.6f}",
		f"accel_norm_avg_g={accel_norm_avg:.6f}",
		f"ax_offset_g={ax_offset:.6f}",
		f"ay_offset_g={ay_offset:.6f}",
		f"az_offset_g={az_offset:.6f}",
		f"gx_offset_dps={gx_offset:.6f}",
		f"gy_offset_dps={gy_offset:.6f}",
		f"gz_offset_dps={gz_offset:.6f}",
		f"gz_stddev_dps={stddev(gz_list, gz_avg):.6f}",
	]

	with open(out_path, "w", encoding="utf-8") as fp:
		fp.write("\n".join(lines) + "\n")

	print(f"Calibration done. samples={n}")
	print(f"Saved: {out_path}")


if __name__ == "__main__":
	main()
