from __future__ import annotations

import argparse
import shutil
from pathlib import Path

try:
	from ultralytics import YOLO
except ImportError as exc:
	raise SystemExit(
		"Ultralytics is not installed. Install it with: pip install ultralytics"
	) from exc


def prefer_primary_path(primary: str) -> Path:
	base_dir = Path(__file__).resolve().parent
	primary_path = base_dir / primary
	if primary_path.exists():
		return primary_path

	parts = Path(primary).parts
	if len(parts) >= 2:
		return base_dir / Path(*parts[1:])

	return primary_path


def default_dataset_yaml() -> Path:
	return prefer_primary_path("road/dataset/rugd_yolo_seg/dataset.yaml")


def default_model_path() -> Path:
	return prefer_primary_path("road/model/02_yolo11m-road-type-sg.pt")


def parse_args() -> argparse.Namespace:
	parser = argparse.ArgumentParser(
		description="Train YOLO segmentation model using converted RUGD dataset."
	)
	parser.add_argument(
		"--data",
		type=Path,
		default=default_dataset_yaml(),
		help="Path to dataset.yaml generated by conversion script.",
	)
	parser.add_argument(
		"--model",
		type=Path,
		default=default_model_path(),
		help="Path to segmentation checkpoint (.pt).",
	)
	parser.add_argument("--epochs", type=int, default=100, help="Training epochs.")
	parser.add_argument("--imgsz", type=int, default=640, help="Input image size.")
	parser.add_argument("--batch", type=int, default=8, help="Batch size.")
	parser.add_argument("--workers", type=int, default=8, help="Number of dataloader workers.")
	parser.add_argument("--patience", type=int, default=30, help="Early stopping patience.")
	parser.add_argument("--device", type=str, default="0", help="CUDA device index or 'cpu'.")
	parser.add_argument("--project", type=Path, default=Path("road/runs"), help="Run root dir.")
	parser.add_argument("--name", type=str, default="rugd-road-seg", help="Run name.")
	parser.add_argument("--seed", type=int, default=42, help="Random seed.")
	parser.add_argument(
		"--cache",
		action="store_true",
		help="Cache images for faster training (uses more RAM/disk).",
	)
	parser.add_argument(
		"--no-amp",
		action="store_true",
		help="Disable mixed precision training.",
	)
	return parser.parse_args()


def validate_paths(data_yaml: Path, model_path: Path) -> None:
	if not data_yaml.exists():
		raise FileNotFoundError(f"dataset.yaml not found: {data_yaml}")
	if not model_path.exists():
		raise FileNotFoundError(f"model checkpoint not found: {model_path}")


def main() -> None:
	args = parse_args()
	validate_paths(args.data, args.model)

	print("Starting YOLO segmentation training...")
	print(f"Dataset: {args.data}")
	print(f"Model: {args.model}")
	print(f"Device: {args.device}")

	model = YOLO(str(args.model))
	results = model.train(
		data=str(args.data),
		epochs=args.epochs,
		imgsz=args.imgsz,
		batch=args.batch,
		workers=args.workers,
		patience=args.patience,
		device=args.device,
		project=str(args.project),
		name=args.name,
		seed=args.seed,
		cache=args.cache,
		amp=not args.no_amp,
	)

	print("Training complete.")
	if getattr(results, "save_dir", None):
		print(f"Artifacts: {results.save_dir}")
		best_weights = Path(results.save_dir) / "weights" / "best.pt"
		if best_weights.exists():
			args.model.parent.mkdir(parents=True, exist_ok=True)
			shutil.copy2(best_weights, args.model)
			print(f"Updated model checkpoint: {args.model}")
		else:
			print(f"best.pt not found, skipping model update: {best_weights}")


if __name__ == "__main__":
	main()
