from __future__ import annotations

import argparse
import shutil
from pathlib import Path
from ultralytics import YOLO 


SOURCE_DIR = Path(__file__).resolve().parent

def prefer_primary_path(primary: str) -> Path:
	base_dir = SOURCE_DIR
	primary_path = base_dir / primary
	if primary_path.exists():
		return primary_path

	parts = Path(primary).parts
	if len(parts) >= 2 and parts[0].lower() == "road":
		return base_dir / Path(*parts[1:])

	return primary_path


def resolve_source_relative_path(path: Path) -> Path:
	if path.is_absolute():
		return path
	return prefer_primary_path(path.as_posix())


def resolve_model_source(model_source: str) -> str:
	model_path = Path(model_source)
	if model_path.is_absolute():
		return str(model_path)

	# Keep ultralytics built-in model names (e.g., yolo11m-seg.yaml) untouched.
	if len(model_path.parts) == 1 and not model_path.exists():
		return model_source

	return str(resolve_source_relative_path(model_path))


def default_dataset_yaml() -> Path:
	return prefer_primary_path("road/dataset/pothole600_yolo_seg/dataset.yaml")


def default_model_source() -> str:
	return "yolo11m-seg.yaml"


def default_output_model_path() -> Path:
	return prefer_primary_path("dataset/model/04-yolo11m-pothole-sg.pt")


def default_project_root() -> Path:
	return prefer_primary_path("dataset/runs")


def parse_args() -> argparse.Namespace:
	parser = argparse.ArgumentParser(
		description="Train YOLO segmentation model using converted pothole600 dataset."
	)
	parser.add_argument(
		"--data",
		type=Path,
		default=default_dataset_yaml(),
		help="Path to dataset.yaml generated by conversion script.",
	)
	parser.add_argument(
		"--model",
		type=str,
		default=default_model_source(),
		help="YOLO model source (.yaml for scratch training or .pt for fine-tuning).",
	)
	parser.add_argument(
		"--output-model",
		type=Path,
		default=default_output_model_path(),
		help="Path where the trained .pt checkpoint will be copied.",
	)
	parser.add_argument("--epochs", type=int, default=100, help="Training epochs.")
	parser.add_argument("--imgsz", type=int, default=640, help="Input image size.")
	parser.add_argument("--batch", type=int, default=8, help="Batch size.")
	parser.add_argument("--workers", type=int, default=8, help="Number of dataloader workers.")
	parser.add_argument("--patience", type=int, default=30, help="Early stopping patience.")
	parser.add_argument("--device", type=str, default="0", help="CUDA device index or 'cpu'.")
	parser.add_argument("--project", type=Path, default=default_project_root(), help="Run root dir.")
	parser.add_argument("--name", type=str, default="pothole600-seg", help="Run name.")
	parser.add_argument("--seed", type=int, default=42, help="Random seed.")
	parser.add_argument(
		"--cache",
		action="store_true",
		help="Cache images for faster training (uses more RAM/disk).",
	)
	parser.add_argument(
		"--no-amp",
		action="store_true",
		help="Disable mixed precision training.",
	)
	return parser.parse_args()


def validate_paths(data_yaml: Path, model_source: str) -> None:
	if not data_yaml.exists():
		raise FileNotFoundError(f"dataset.yaml not found: {data_yaml}")
	model_path = Path(model_source)
	if model_path.suffix == ".pt" and not model_path.exists():
		raise FileNotFoundError(f"model checkpoint not found: {model_path}")


def main() -> None:
	args = parse_args()
	args.data = resolve_source_relative_path(args.data)
	args.output_model = resolve_source_relative_path(args.output_model)
	args.project = resolve_source_relative_path(args.project)
	args.model = resolve_model_source(args.model)
	validate_paths(args.data, args.model)

	print("Starting YOLO segmentation training...")
	print(f"Dataset: {args.data}")
	print(f"Model: {args.model}")
	print(f"Device: {args.device}")

	model = YOLO(args.model)
	results = model.train(
		data=str(args.data),
		epochs=args.epochs,
		imgsz=args.imgsz,
		batch=args.batch,
		workers=args.workers,
		patience=args.patience,
		device=args.device,
		project=str(args.project),
		name=args.name,
		seed=args.seed,
		cache=args.cache,
		amp=not args.no_amp,
	)

	print("Training complete.")

	if getattr(results, "save_dir", None):
		print(f"Artifacts: {results.save_dir}")
		best_weights = Path(results.save_dir) / "weights" / "best.pt"
		if best_weights.exists():
			args.output_model.parent.mkdir(parents=True, exist_ok=True)
			shutil.copy2(best_weights, args.output_model)
			print(f"Saved trained model checkpoint: {args.output_model}")
		else:
			print(f"best.pt not found, skipping model update: {best_weights}")


if __name__ == "__main__":
	main()
