from __future__ import annotations

import argparse
import shutil
import signal
from datetime import datetime
from pathlib import Path

try:
	from ultralytics import YOLO
except ImportError as exc:
	raise SystemExit(
		"Ultralytics is not installed. Install it with: pip install ultralytics"
	) from exc


def prefer_primary_path(primary: str) -> Path:
	base_dir = Path(__file__).resolve().parent
	primary_path = base_dir / primary
	if primary_path.exists():
		return primary_path

	parts = Path(primary).parts
	if len(parts) >= 2:
		return base_dir / Path(*parts[1:])

	return primary_path


def default_dataset_yaml() -> Path:
	return prefer_primary_path("road/dataset/cobot_01_yolo_seg/dataset.yaml")


def default_model_source() -> str:
	return "yolo11m-seg.yaml"


def default_output_model_path() -> Path:
	base_path = prefer_primary_path("road/model/02_yolo11m-cobot-road-type-sg.pt")
	date_suffix = datetime.now().strftime("%y%m%d")
	return base_path.with_name(f"{base_path.stem}-{date_suffix}{base_path.suffix}")


def parse_args() -> argparse.Namespace:
	parser = argparse.ArgumentParser(
		description="Train YOLO segmentation model using converted COBOT dataset."
	)
	parser.add_argument(
		"--data",
		type=Path,
		default=default_dataset_yaml(),
		help="Path to dataset.yaml generated by conversion script.",
	)
	parser.add_argument(
		"--model",
		type=str,
		default=default_model_source(),
		help="YOLO model source (.yaml for scratch training or .pt for fine-tuning).",
	)
	parser.add_argument(
		"--output-model",
		type=Path,
		default=default_output_model_path(),
		help="Path where the trained .pt checkpoint will be copied.",
	)
	parser.add_argument("--epochs", type=int, default=100, help="Training epochs.")
	parser.add_argument("--imgsz", type=int, default=640, help="Input image size.")
	parser.add_argument("--batch", type=int, default=8, help="Batch size.")
	parser.add_argument("--workers", type=int, default=8, help="Number of dataloader workers.")
	parser.add_argument("--patience", type=int, default=30, help="Early stopping patience.")
	parser.add_argument("--device", type=str, default="0", help="CUDA device index or 'cpu'.")
	parser.add_argument("--project", type=Path, default=Path("road/runs"), help="Run root dir.")
	parser.add_argument("--name", type=str, default="cobot-road-seg", help="Run name.")
	parser.add_argument("--seed", type=int, default=42, help="Random seed.")
	parser.add_argument(
		"--cache",
		action="store_true",
		help="Cache images for faster training (uses more RAM/disk).",
	)
	parser.add_argument(
		"--no-amp",
		action="store_true",
		help="Disable mixed precision training.",
	)
	parser.add_argument(
		"--resume",
		action="store_true",
		help="Resume training from the last checkpoint in the run directory.",
	)
	parser.add_argument(
		"--resume-path",
		type=Path,
		default=None,
		help="Explicit path to checkpoint to resume from (e.g., runs/cobot-road-seg/weights/last.pt).",
	)
	return parser.parse_args()


def validate_paths(data_yaml: Path, model_source: str) -> None:
	if not data_yaml.exists():
		raise FileNotFoundError(f"dataset.yaml not found: {data_yaml}")
	model_path = Path(model_source)
	if model_path.suffix == ".pt" and not model_path.exists():
		raise FileNotFoundError(f"model checkpoint not found: {model_path}")


def find_last_checkpoint(project_dir: Path, run_name: str) -> Path | None:
	"""Find the last.pt checkpoint in the run directory."""
	checkpoint_path = project_dir / run_name / "weights" / "last.pt"
	if checkpoint_path.exists():
		return checkpoint_path
	return None


def resume_or_new_model(args: argparse.Namespace) -> tuple[YOLO, bool]:
	"""
	Determine if we should resume from checkpoint or train fresh.
	Returns: (model, is_resuming)
	"""
	# Resume is allowed only when --resume is explicitly enabled.
	if args.resume:
		if args.resume_path:
			if args.resume_path.exists():
				print(f"Resuming from explicit checkpoint: {args.resume_path}")
				return YOLO(str(args.resume_path)), True
			print(f"--resume-path not found: {args.resume_path}")
			print("Falling back to auto-discovered last checkpoint...")

		last_checkpoint = find_last_checkpoint(args.project, args.name)
		if last_checkpoint:
			print(f"Resuming from last checkpoint: {last_checkpoint}")
			return YOLO(str(last_checkpoint)), True

		print(f"--resume flag set but no checkpoint found in {args.project / args.name}")
		print("Starting fresh training...")
	elif args.resume_path:
		print("--resume-path was provided but --resume is False, so starting fresh training.")
	
	# Start fresh
	print(f"Starting fresh training with model: {args.model}")
	return YOLO(str(args.model)), False


def main() -> None:
	args = parse_args()
	validate_paths(args.data, args.model)

	print("Starting YOLO segmentation training...")
	print(f"Dataset: {args.data}")
	print(f"Device: {args.device}")
	
	# Load model (fresh or resume from checkpoint)
	model, is_resuming = resume_or_new_model(args)
	
	# Set up signal handler for graceful interruption
	def signal_handler(signum, frame):
		print("\n\nTraining interrupted by user (Ctrl-C).")
		print(f"To resume: python {Path(__file__).name} --resume --name {args.name}")
		print("(The last.pt checkpoint will be automatically loaded.)")
		raise KeyboardInterrupt()
	
	signal.signal(signal.SIGINT, signal_handler)

	results = model.train(
		data=str(args.data),
		epochs=args.epochs,
		imgsz=args.imgsz,
		batch=args.batch,
		workers=args.workers,
		patience=args.patience,
		device=args.device,
		project=str(args.project),
		name=args.name,
		seed=args.seed,
		cache=args.cache,
		amp=not args.no_amp,
		resume=is_resuming,  # Resume if we loaded from checkpoint
	)

	print("Training complete.")
	if getattr(results, "save_dir", None):
		print(f"Artifacts: {results.save_dir}")
		best_weights = Path(results.save_dir) / "weights" / "best.pt"
		if best_weights.exists():
			args.output_model.parent.mkdir(parents=True, exist_ok=True)
			shutil.copy2(best_weights, args.output_model)
			print(f"Updated model checkpoint: {args.output_model}")
		else:
			print(f"best.pt not found, skipping model update: {best_weights}")


if __name__ == "__main__":
	main()
